Repository fireblocks/fireblocks-sdk-js, pull requests merged in 2023-01, with the labels that each got.

#134 fix incorrect interfaces
  src/fireblocks-sdk.ts
  src/types.ts
Labels: bug, breaking

#130 Feat/web3 api phase B
  package-lock.json
  package.json
  src/fireblocks-sdk.ts
  src/types.ts
Labels: enhancement, breaking

#135 Add User-Agent HTTP header
  README.md
  package-lock.json
  package.json
  src/api-client.ts
  src/fireblocks-sdk.ts
  tsconfig.json
Labels: documentation, enhancement, chore

#138 Revert #135
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
  src/api-client.ts
  src/fireblocks-sdk.ts
  tsconfig.json
Labels: bug, chore

#139 Add User-Agent HTTP header (no package version)
  README.md
  package-lock.json
  package.json
  src/api-client.ts
  src/fireblocks-sdk.ts
Labels: enhancement, chore

#140 User agent version
  .github/workflows/node.js.yml
  .github/workflows/publish-npm.yml
  README.md
  package.json
  src/api-client.ts
  src/fireblocks-sdk.ts
  tsconfig.json
Labels: chore
