Repository fireblocks/fireblocks-sdk-js, pull requests merged in 2023-05, with the labels that each got.

#157 Add Travel Rule message to Transaction request and PII Encryption
  .github/workflows/node.js.yml
  .gitignore
  README.md
  docs/V4-MIGRATION.md
  package-lock.json
  package.json
  src/fireblocks-sdk.ts
  src/pii-client.ts
  src/types.ts
  tsconfig.json
Labels: enhancement, dependencies, chore, breaking

#165 Make travelRuleOptions field optional
  README.md
  src/fireblocks-sdk.ts
Labels: chore

#167 Remove Travel Rule feature
  README.md
  package-lock.json
  package.json
  src/fireblocks-sdk.ts
  src/pii-client.ts
  src/types.ts
Labels: enhancement, chore

#168 Roll back remove of Travel Rule message create and Pii encryption of…
  README.md
  package-lock.json
  package.json
  src/fireblocks-sdk.ts
  src/pii-client.ts
  src/types.ts
Labels: chore

#171 Removal of Travel Rule
  README.md
  package-lock.json
  package.json
  src/fireblocks-sdk.ts
  src/pii-client.ts
  src/types.ts
Labels: chore

#172 Fix endpoint /v1/tokenization/tokens/${assetId}/link
  src/fireblocks-sdk.ts
Labels: bug
