Repository fireblocks/fireblocks-sdk-js, pull requests merged in 2024-02, with the labels that each got.

#256 Tokenization - adding assetId as an option for creating a new EVM token
  src/types.ts
Labels: enhancement

#261 Fix link to API Reference
  README.md
Labels: bug, chore

#260 staking-sdk: fix PositionStatus missing statuses, StakeResponse respo…
  src/fireblocks-sdk.ts
  src/staking/staking-api-client.ts
  src/staking/staking-sdk.ts
  src/staking/types.ts
Labels: bug
